# Generated by Django 6.0.6 on 2026-06-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userresponse_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='careersuggestion',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
