# Generated by Django 6.0.6 on 2026-06-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_careersuggestion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapstep',
            name='deep_dive',
            field=models.TextField(blank=True, null=True),
        ),
    ]
